libdlna: fix build with ffmpeg 2.4.2
fixes error:
src/libdlna.so: undefined reference to `av_find_stream_info'
src/libdlna.so: undefined reference to `av_close_input_file'
collect2: error: ld returned 1 exit status

ffmpeg API changes:
av_find_stream_info -> avformat_find_stream_info
av_close_input_file -> avformat_close_input

patch libdlna instead of ffmpeg since recently
av_close_input_file got removed in upstream git
avformat: remove obsolete FF_API_CLOSE_INPUT_FILE cruft

Signed-off-by: Dirk Neukirchen <plntyk.lede@plntyk.name>