flow-tools: fix gcc5 build
gcc5 uses -std=gnu11 instead of -std=gnu89
by default

changed inline semantic leads to link errors:
 undefined reference to `eval_match_src_as'

Signed-off-by: Dirk Neukirchen <plntyk.lede@plntyk.name>