anyremote: update to 6.6.1
- add missing signal.h include
fixes compile error:
pr_web.c: In function 'serveRequest':
pr_web.c:1127:5: warning: implicit declaration of function 'signal' [-Wimplicit-function-declaration]
     signal(SIGPIPE, SIG_IGN);  // why id did not inherit this ?
     ^
pr_web.c:1127:12: error: 'SIGPIPE' undeclared (first use in this function)
     signal(SIGPIPE, SIG_IGN);  // why id did not inherit this ?
            ^
pr_web.c:1127:12: note: each undeclared identifier is reported only once for each function it appears in
pr_web.c:1127:21: error: 'SIG_IGN' undeclared (first use in this function)
     signal(SIGPIPE, SIG_IGN);  // why id did not inherit this ?

Signed-off-by: Dirk Neukirchen <plntyk.lede@plntyk.name>