procmail: fix missing library
fix build error (mips64,glibc,gcc49):
misc.o: In function `conditions':
misc.c:(.text+0x1794): undefined reference to `pow'

Signed-off-by: Dirk Neukirchen <plntyk.lede@plntyk.name>